In [1]:
from lxml import etree
import numpy as np

In [2]:
# Parse the XML file
tree = etree.parse('instances/NL4.xml')
root = tree.getroot()

# Get number of teams
teams = root.xpath('.//Teams/team')
num_teams = len(teams)

# Initialize the distance matrix
distances = np.zeros((num_teams, num_teams), dtype=int)

# Fill the matrix with distances
for dist_elem in root.xpath('.//Distances/distance'):
    t1 = int(dist_elem.get('team1'))
    t2 = int(dist_elem.get('team2'))
    dist = int(dist_elem.get('dist'))
    distances[t1, t2] = dist

print(distances)


[[  0 745 665 929]
 [745   0  80 337]
 [665  80   0 380]
 [929 337 380   0]]
